Feature/new syscall tests cases
Lind-Project/lind_project pull request #306
Opened 2023-06-09 22:16 UTC by kpan2034

Added tests for the following syscalls:

- pipe2
- getifaddrs
- getppid
- mkdir
- rmdir
- access

2023-06-12 23:14 UTC, rennergade commented
We should hook these up to the test suite before we merge them. I'll let the team review the individual tests for now.

2023-06-14 17:15 UTC, RusherRG requested changes

2023-06-14 19:15 UTC, rennergade commented on tests/test_cases/getppid.c
> +#undef _GNU_SOURCE
Yes definitely.

2023-06-14 19:35 UTC, rennergade commented
Also naming the test cases that handle two syscalls so we know that off the bat would be good. IE "access" should be "creat_access"

2023-06-14 19:40 UTC, kpan2034 commented on tests/test_cases/getppid.c
> +#undef _GNU_SOURCE
Alright, will work on this.

2023-07-15 00:03 UTC, RusherRG commented on tests/test_cases/getppid.c
> +#undef _GNU_SOURCE
Awesome, this looks good. :tada:

2023-07-15 00:04 UTC, RusherRG requested changes

2023-07-15 00:04 UTC, RusherRG commented on tests/test_cases/pipe2.py
> +    exit(-1)
Make sure to end all your test files with a new line.

2023-07-15 00:04 UTC, RusherRG commented on tests/test_cases/getifaddrs.py
> +    verify(line)
Make sure to end all your test files with a new line.

2023-07-15 00:04 UTC, RusherRG commented on tests/test_cases/getppid.c
> +}
Make sure to end all your test files with a new line.

2023-07-15 00:13 UTC, RusherRG requested changes

2023-07-15 00:13 UTC, RusherRG commented on tests/test_cases/pipe2.py
Can you also add checks for the return value of read and write? Both of them should be 3(number of bytes read/write)

2023-07-15 15:53 UTC, kuzeyardabulut commented on tests/test_cases/getppid.c
> +  fflush(stdout);
Why we are using `fflush()` in here ?

2023-07-15 15:55 UTC, kuzeyardabulut commented
You should `fflush(stdout)` after doing printfs.

2023-07-15 15:55 UTC, kuzeyardabulut requested changes
You should `fflush(stdout)` after doing printfs.

2023-07-16 17:07 UTC, rennergade commented on tests/test_cases/pipe2.py
> +        exit(-1)
needs newline

2023-07-16 17:07 UTC, rennergade commented on tests/test_cases/pipe2.py
that would be good

2023-07-16 17:07 UTC, rennergade commented on tests/test_cases/pipe2.c
> +  printf("read() ret: %d\n", ret);
add fflushes

2023-07-16 19:34 UTC, kuzeyardabulut requested changes

2023-07-16 19:34 UTC, kuzeyardabulut commented on tests/test_cases/creat_access.c
> +  fflush(stdout);
Do we need this?

2023-07-16 19:34 UTC, kuzeyardabulut commented on tests/test_cases/getppid.c
> +  int f = fork();
I think it would be better to delete such short comment lines.

2023-07-16 20:07 UTC, merged